### ISSUE TITLE
FileNotFoundError out_final.mp4

### ISSUE THREAD

**Issue by voltrevo** [lagmoellertim/unsilence#148]
**Describe the bug**

Using a completely vanilla/default invocation (except `--debug`, issue also happens without `--debug`) of unsilence on Amazon Linux, it crashes it with `FileNotFound`:

```
[ec2-user@ip-172-31-42-91 ~]$ unsilence --debug input.mp4 output.mp4
Calculating Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00

┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Type     ┃ Before          ┃ After           ┃ Difference        ┃
┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ Combined │ 0:03:00 (100%)  │ 0:01:57 (65.1%) │ -0:01:03 (-34.9%) │
│ Audible  │ 0:01:45 (58.1%) │ 0:01:45 (58.1%) │ 0:00:00 (0.0%)    │
│ Silent   │ 0:01:15 (41.9%) │ 0:00:13 (7.0%)  │ -0:01:03 (-34.9%) │
└──────────┴─────────────────┴─────────────────┴───────────────────┘

[?] Continue with these options? (Y/n) y
Rendering Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
Combining Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/usr/lib64/python3.7/shutil.py", line 566, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/.tmp/45c670ce-03e7-4d50-b540-e07c7a616810/out_final.mp4' -> '/home/ec2-user/output.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/unsilence", line 33, in <module>
    sys.exit(load_entry_point('unsilence==1.0.9', 'console_scripts', 'unsilence')())
  File "/usr/local/lib/python3.7/site-packages/unsilence-1.0.9-py3.7.egg/unsilence/command_line/EntryPoint.py", line 21, in main
  File "/usr/local/lib/python3.7/site-packages/unsilence-1.0.9-py3.7.egg/unsilence/command_line/EntryPoint.py", line 107, in run
  File "/usr/local/lib/python3.7/site-packages/unsilence-1.0.9-py3.7.egg/unsilence/Unsilence.py", line 105, in render_media
  File "/usr/local/lib/python3.7/site-packages/unsilence-1.0.9-py3.7.egg/unsilence/lib/render_media/MediaRenderer.py", line 138, in render
  File "/usr/lib64/python3.7/shutil.py", line 580, in move
    copy_function(src, real_dst)
  File "/usr/lib64/python3.7/shutil.py", line 266, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/.tmp/45c670ce-03e7-4d50-b540-e07c7a616810/out_final.mp4'
```

This appears to be related to #17, but that was believed to be solved by #8. This is still happening to me using the currently latest master (f113336).

**To Reproduce**

1. Use an amazon linux t3.nano
2. Install ffmpeg using this guide: https://www.maskaravivek.com/post/how-to-install-ffmpeg-on-ec2-running-amazon-linux
3. `sudo yum update && sudo yum install git`
4. Install unsilence from source as per repo instructions
5. `unsilence input.mp4 output.mp4`

**Expected behavior**

Should generate `output.mp4` with silences sped up.

**Desktop (please complete the following information):**
 - OS + version: Amazon Linux amzn2-ami-kernel-5.10-hvm-2.0.20220606.1-x86_64-gp2
ami-07620139298af599e
 - Python version: 3.7.16
 - FFMPEG version: 5.1.1-static https://johnvansickle.com/ffmpeg/

**Comment by voltrevo** [comment]
Doing some investigation, I think this is an issue of process management. Subprocesses are failing but this isn't getting surfaced.

I didn't have `ffprobe` set up, but the project relies on it. Maybe it goes without saying that having `ffmpeg` means also having this tool, but it's unclear to me being relatively unfamiliar with `ffmpeg`.

I've also found that some of the `ffmpeg` invocations are getting killed, probably because a t3.nano doesn't have enough memory.

Retrying with fixes to the above problems, but I think the bug is still valid - unsilence should be bubbling up these errors, without them it's taking a long time to track this down.

**Comment by voltrevo** [comment]
Yep that fixed the problem. This is a bug about not reporting/detecting subprocess failures.

**Comment by Seishirou101** [comment]
Hello, I have the same issue but I'm on a windows installation using anaconda with python 3.9.13, and ffmpeg 4.3.1. It seems like my ffprobe is setup correctly cause I can invoke it, but i'm not sure how to confirm if any ffmpeg invocations are being killed as I believe I have enough memory. What exactly did you do to remedy these issues?

**Comment by voltrevo** [comment]
@Seishirou101 For me it was just ffprobe and running on a bigger ec2 instance.

I'd recommend running via "Installation as library (from source)". That way you can edit the code to do some troubleshooting (re-run the setup.py part after editing code).

Try looking at the `.tmp` files. They should be video segments, and you get unreasonably small ones (48 bytes) when this issue occurs.

Then print the commands used to generate the files. For any files that are messed up, try running them manually to see if you can get more detail.

**Comment by renatovico** [comment]
I finnaly understand the bug, tihs occurs because the unsilence need ffmpeg  be at least v6, in version 7 ffmpeg change the parameters, and unsilence does not expect this kind of fail in the subprocess managment, i tried port to new version, but does not have success,  point the problem here for future reference
