### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by dilsonpereira** [lagmoellertim/unsilence#4]
Hi! I get the following error when trying to use unsilence. Thank you!

```
Rendering Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00  
Combining Intervals... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--  
Traceback (most recent call last):
  File "/usr/lib/python3.9/shutil.py", line 803, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dilson/Documentos/.tmp/6af8866c-3d1f-4139-abbc-839bba6da3a7/out_final.mp4' -> '/home/dilson/Documentos/teste.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dilson/.local/bin/unsilence", line 11, in <module>
    sys.exit(main())
  File "/home/dilson/.local/lib/python3.9/site-packages/unsilence/command_line/EntryPoint.py", line 19, in main
    run()
  File "/home/dilson/.local/lib/python3.9/site-packages/unsilence/command_line/EntryPoint.py", line 101, in run
    continual.render_media(
  File "/home/dilson/.local/lib/python3.9/site-packages/unsilence/Unsilence.py", line 96, in render_media
    renderer.render(self.__input_file, output_file, self.__intervals, **kwargs)
  File "/home/dilson/.local/lib/python3.9/site-packages/unsilence/lib/render_media/MediaRenderer.py", line 125, in render
    shutil.move(final_output, output_file)
  File "/usr/lib/python3.9/shutil.py", line 817, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.9/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dilson/Documentos/.tmp/6af8866c-3d1f-4139-abbc-839bba6da3a7/out_final.mp4'
```

**Comment by orestisfl** [comment]
Maybe you could detect the version in unsilence & exit with an error?

You can get the version with `ffmpeg -version`.

**Comment by lagmoellertim** [comment]
Good Idea, I'm going to implement that!

**Comment by TSSlade** [comment]
I'm having a similar situation on MacOS Catalina despite having ffmpeg > 4.2:

```
± in ~/projects/w210_capstone/teacherprints → ffmpeg -version                                                                                                                          ▸▸▸▸▸▸▸▹▹▹
ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
built with clang version 9.0.1
configuration: --prefix=/Users/tsslade/miniconda3/envs/teacherprints --cc=x86_64-apple-darwin13.4.0-clang --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100
```

Given the command `u.render_media("engage-ny-147641946_dampened.wav", audible_volume=2, silent_volume=0)`

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/miniconda3/envs/teacherprints/lib/python3.8/shutil.py in move(src, dst, copy_function)
    787     try:
--> 788         os.rename(src, real_dst)
    789     except OSError:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/tsslade/Dropbox/BerkeleyMIDS/projects/w210_capstone/teacherprints/vandam_practice/mp3/.tmp/a1e63f44-2e59-4bfb-be0e-c86cb4b420cb/out_final.wav' -> '/Users/tsslade/Dropbox/BerkeleyMIDS/projects/w210_capstone/teacherprints/vandam_practice/mp3/engage-ny-147641946_dampened.wav'

During handling of the above exception, another exception occurred:

FileNotFoundError                         Traceback (most recent call last)
<ipython-input-12-697c30a817e1> in <module>
----> 1 u.render_media("engage-ny-147641946_dampened.wav", audible_volume=2, silent_volume=0)

~/miniconda3/envs/teacherprints/lib/python3.8/site-packages/unsilence/Unsilence.py in render_media(self, output_file, **kwargs)
    107 
    108         renderer = MediaRenderer(self.__temp_dir)
--> 109         renderer.render(self.__input_file, output_file, self.__intervals, **kwargs)
    110 
    111     def cleanup(self):

~/miniconda3/envs/teacherprints/lib/python3.8/site-packages/unsilence/lib/render_media/MediaRenderer.py in render(self, input_file, output_file, intervals, **kwargs)
    129         )
    130 
--> 131         shutil.move(final_output, output_file)
    132         shutil.rmtree(video_temp_path)
    133 

~/miniconda3/envs/teacherprints/lib/python3.8/shutil.py in move(src, dst, copy_function)
    800             rmtree(src)
    801         else:
--> 802             copy_function(src, real_dst)
    803             os.unlink(src)
    804     return real_dst

~/miniconda3/envs/teacherprints/lib/python3.8/shutil.py in copy2(src, dst, follow_symlinks)
    430     if os.path.isdir(dst):
    431         dst = os.path.join(dst, os.path.basename(src))
--> 432     copyfile(src, dst, follow_symlinks=follow_symlinks)
    433     copystat(src, dst, follow_symlinks=follow_symlinks)
    434     return dst

~/miniconda3/envs/teacherprints/lib/python3.8/shutil.py in copyfile(src, dst, follow_symlinks)
    259         os.symlink(os.readlink(src), dst)
    260     else:
--> 261         with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    262             # macOS
    263             if _HAS_FCOPYFILE:

FileNotFoundError: [Errno 2] No such file or directory: '/Users/tsslade/Dropbox/BerkeleyMIDS/projects/w210_capstone/teacherprints/vandam_practice/mp3/.tmp/a1e63f44-2e59-4bfb-be0e-c86cb4b420cb/out_final.wav'
```

I installed unsilence via `pip install unsilence` about 30 minutes ago. Not sure whether it's up-to-date with your 1.0.3 or not.

**Comment by TSSlade** [comment]
FWIW, it appears the issue may have been related to my working with a strictly audio input. When I issue the same command, but with the `-ao` flag enabled, I encounter no problems: `unsilence engage-ny-147641946.wav engage-ny-147641946_dampened.wav -ao -av 1 -sv 0`
